name = "neoflux"
license = "GPL-3.0-only"
licenselink = "https://github.com/NhProGamer/neoflux/blob/main/LICENSE"
description = "neoflux is a hugo theme made by myself ! "
homepage = "https://github.com/NhProGamer/neoflux"
demosite = ""

tags = ["blog", "responsive", "clean", "personal"]

features = []

min_version = "0.123.0"

[author]
name = "Néo Huyghe"
homepage = "https://nhsoul.fr"
